controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute

authentication_token:
  path: /api/login
  methods: ["POST"]

app.swagger_ui:
  path: /api/docs
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

uploaded_file:
  path: /uploads/{filename}
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
  defaults:
    url: "%kernel.project_dir%/public/uploads/{filename}"
