version: "3.8"

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf
      - frontend_volume:/usr/share/nginx/html
      - backend_volume:/var/www
    depends_on:
      - frontend
      - backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    volumes:
      - frontend_volume:/var/lib/frontend
    environment:
      REACT_APP_API_URL: http://localhost:80
      REACT_APP_SOCKET_URL: http://localhost:8080
    depends_on:
      - backend

  backend:
    build:
      args:
        user: docker-user
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    working_dir: /var/www/
    volumes:
      - ./backend:/var/www
      - backend_volume:/var/www
    environment:
      APP_ENV: prod
      DATABASE_URL: mysql://root:root@db:3306/hackmapa
    depends_on:
      - db

  nodejs:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: nodejs-socket
    ports:
      - "8080:8080"
    environment:
      PORT: 8080

  db:
    image: mysql:5.7
    container_name: db
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_USER: hackmapa
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8081:80"
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
      PMA_ARBITRARY: 1
    depends_on:
      - db

volumes:
  frontend_volume:
  backend_volume:
  db-data:

networks:
  default:
    driver: bridge
