version: "3.8"

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf
      - frontend_volume:/usr/share/nginx/html
      - backend_volume:/var/www
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - frontend
      - backend

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --email corentinancel@gmail.com -d hackmapa.fr --agree-tos

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL=""
        - REACT_APP_SOCKET_URL=":8081"
    volumes:
      - frontend_volume:/var/lib/frontend
    environment:
      - REACT_APP_API_URL=""
      - REACT_APP_SOCKET_URL=":8081"
    depends_on:
      - backend
    env_file:
      - ./frontend/.env.production

  backend:
    build:
      args:
        user: docker-user
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    working_dir: /var/www/
    volumes:
      - ./backend:/var/www
      - backend_volume:/var/www
    environment:
      APP_ENV: prod
      DATABASE_URL: mysql://root:root@db:3306/hackmapa
    depends_on:
      - db

  nodejs:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: nodejs-socket
    ports:
      - "8081:8081"
    environment:
      PORT: 8081

  db:
    image: mariadb
    container_name: db
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin
    restart: always
    container_name: phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
      - MEMORY_LIMIT=512M
      - UPLOAD_LIMIT=512M
      - PHP_MAX_EXECUTION_TIME=3600
      - PMA_HOST=db
    depends_on:
      - db

volumes:
  frontend_volume:
  backend_volume:
  db-data:

networks:
  default:
    driver: bridge
