version: "3.8"

services:
  frontend:
    build:
      context: ./playground-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:8000
      REACT_APP_SOCKET_URL: http://localhost:8080

  backend:
    build:
      context: ./playground-backend
      dockerfile: Dockerfile
    environment:
      APP_ENV: dev
      DATABASE_URL: mysql://root:root@db:3306/hackmapa
    ports:
      - "8000:8000"
    tty: true

  nodejs:
    build:
      context: ./playground-server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      PORT: 8080

  db:
    image: mysql:5.7
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hackmapa
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - db

volumes:
  db-data:

networks:
  default:
    driver: bridge
