name: Deploy

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            "cd ${{ secrets.PATH }} && git checkout ${{ secrets.MAIN_BRANCH }} && git pull && docker compose down && docker volume ls | grep playground_frontend_volume && docker volume rm playground_frontend_volume || echo 'No volume to remove' &&
            docker compose up --build -d && bash migrate.sh && exit"
